import { Language } from "./types";

export const ICONS = {
    SUN: 'M12 3v1m0 16v1m8.66-15.66l-.707.707M4.04 19.96l-.707.707M21 12h-1M4 12H3m15.66 8.66l-.707-.707M4.04 4.04l-.707-.707',
    MOON: 'M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z',
    LOGOUT: 'M17 16l4-4m0 0l-4-4m4 4H7m6-11v2a3 3 0 01-3 3H7',
    USER: 'M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z',
    MENU: 'M4 6h16M4 12h16m-7 6h7',
    CLOSE: 'M6 18L18 6M6 6l12 12',
    CLOUD: 'M17.5 19H9.25A5.25 5.25 0 014 13.75 5.25 5.25 0 019.25 8.5h.55a8 8 0 0115.36 2.44A5.25 5.25 0 0117.5 19z',
    DROPLET: 'M12 2.69l5.66 5.66a8 8 0 11-11.31 0L12 2.69z',
    THERMOMETER: 'M8 14.5V5a4 4 0 118 0v9.5a6 6 0 11-8 0z',
    LEAF: 'M14.12 10.47a3 3 0 00-4.24 0l-1.42 1.41a3 3 0 000 4.24l.71.71a3 3 0 004.24 0l3.54-3.53a3 3 0 000-4.24zM12 18.59l-2.12-2.12a1 1 0 010-1.42l.71-.71a1 1 0 011.41 0L12 14.41l3.54-3.54a1 1 0 011.41 0l.71.71a1 1 0 010 1.41L13.41 17.17l-.71.71a1 1 0 01-1.42 0z',
    RAIN: 'M17.5 19H9.25a5.25 5.25 0 01-5.25-5.25A5.25 5.25 0 019.25 8.5h.55a8 8 0 0115.36 2.44A5.25 5.25 0 0117.5 19zM12 14v5M8 14v5M16 14v5',
    PHONE: 'M20.01 15.38c-1.23 0-2.42-.2-3.53-.56a.976.976 0 00-.93.24l-1.9 1.9c-2.83-1.45-5.15-3.76-6.59-6.59l1.9-1.9a.976.976 0 00.24-.93C8.78 6.42 8.58 5.23 8.58 4c0-.55-.45-1-1-1H4.01c-.55 0-1 .45-1 1 0 9.39 7.61 17 17 17 .55 0 1-.45 1-1v-3.59c0-.55-.45-1-1-1z',
    OTP: 'M4 8h16M4 16h16M8 4l8 16M16 4l-8 16',
    GOOGLE: 'M20.94 11.12c0-.78-.07-1.53-.2-2.26H12v4.26h5.02c-.22 1.38-1.53 3.32-5.02 3.32-3.03 0-5.49-2.5-5.49-5.51s2.46-5.51 5.49-5.51c1.72 0 2.86.73 3.52 1.36l3.24-3.13C16.99 3.37 14.7 2 12 2 6.48 2 2 6.48 2 12s4.48 10 10 10c5.77 0 9.84-4.13 9.84-9.84a9.14 9.14 0 00-.9-3.04z',
    CHAT: 'M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z',
    AI_ASSISTANT: 'M12 8V4m0 16v-4m8-8h-4m-8 0H4m12 0l-3.35-3.35M8.65 8.65L5.3 5.3M15.35 8.65l3.35-3.35M8.65 15.35L5.3 18.7M15.35 15.35l3.35 3.35',
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  [Language.EN]: {
    'appTitle': 'AgroSmart',
    'loginTitle': 'Welcome Back',
    'loginSubtitle': 'Login to your dashboard via OTP',
    'mobileLabel': 'Mobile Number',
    'otpLabel': 'OTP',
    'sendOtpButton': 'Send OTP',
    'verifyButton': 'Verify & Login',
    'logout': 'Logout',
    'welcome': 'Welcome',
    'dashboardTitle': 'Farmer Dashboard',
    'weather': 'Weather',
    'temperature': 'Temperature',
    'humidity': 'Humidity',
    'rainfall': 'Rainfall',
    'soilHealth': 'Soil Health',
    'moisture': 'Moisture',
    'waterStorage': 'Water Storage',
    'tankLevel': 'Tank Level',
    'liters': 'Liters',
    'cropRecommendation': 'Crop Recommendation',
    'getRecommendation': 'Get Recommendation',
    'season': 'Season',
    'soilType': 'Soil Type',
    'altitude': 'Altitude (meters)',
    'selectSeason': 'Select Season',
    'kharif': 'Kharif',
    'rabi': 'Rabi',
    'zaid': 'Zaid',
    'selectSoil': 'Select Soil Type',
    'alluvial': 'Alluvial',
    'black': 'Black',
    'red': 'Red',
    'laterite': 'Laterite',
    'marketPrices': 'Market Prices',
    'crop': 'Crop',
    'price': 'Price (per quintal)',
    'change': 'Change',
    'iotData': 'IoT Sensor Data',
    'communityForum': 'Community Forum',
    'title': 'Title',
    'author': 'Author',
    'replies': 'Replies',
    'loadingRecommendations': 'Getting recommendations from our experts...',
    'recommendationError': 'Could not fetch recommendations. Please try again.',
    'recommendationsForYou': 'Recommendations for you',
    'loadingWeather': 'Loading weather...',
    'weatherError': 'Could not fetch weather data.',
    'lastUpdated': 'Last updated',
    'mobilePlaceholder': 'Enter 10-digit mobile number',
    'otpPlaceholder': 'Enter 4-digit OTP',
    'otpSent': 'OTP sent successfully to your mobile!',
    'invalidOtp': 'Invalid OTP. Please try again.',
    'invalidMobile': 'Please enter a valid 10-digit mobile number.',
    'resendOtp': 'Resend OTP',
    'advertisements': 'Featured Products',
    'loadAds': 'Show Products',
    'loadingAds': 'Loading products...',
    'adsError': 'Could not load advertisements.',
    'learnMore': 'Learn More',
    'governmentSchemes': 'Government Schemes',
    'loadingSchemes': 'Loading schemes...',
    'schemesError': 'Could not load schemes.',
    'issuingBody': 'Issuing Body',
    'benefits': 'Key Benefits',
    'eligibility': 'Eligibility',
    'officialLink': 'Official Link',
    'chat': 'Chat',
    'searchUsers': 'Search users...',
    'newGroup': 'New Group',
    'createGroup': 'Create Group',
    'groupName': 'Group Name',
    'selectMembers': 'Select Members',
    'create': 'Create',
    'cancel': 'Cancel',
    'typeMessage': 'Type a message...',
    'noConversation': 'Select a conversation to start chatting',
    'yearlyRainfallPrediction': 'Yearly Rainfall Prediction',
    'locationJorethang': 'Jorethang, Sikkim',
    'rainfall_mm': 'Rainfall (mm)',
    'aiAssistant': 'Agro Assistant',
    'aiWelcomeMessage': 'Hello! I am your Agro Assistant. How can I help you with your farming today?',
    'aiError': 'Sorry, I am having trouble connecting. Please try again later.',
  },
  [Language.HI]: {
    'appTitle': 'एग्रोस्मार्ट',
    'loginTitle': 'वापसी पर स्वागत है',
    'loginSubtitle': 'OTP के माध्यम से अपने डैशबोर्ड पर लॉगिन करें',
    'mobileLabel': 'मोबाइल नंबर',
    'otpLabel': 'ओटीपी',
    'sendOtpButton': 'ओटीपी भेजें',
    'verifyButton': 'सत्यापित करें और लॉग इन करें',
    'logout': 'लॉग आउट',
    'welcome': 'स्वागत',
    'dashboardTitle': 'किसान डैशबोर्ड',
    'weather': 'मौसम',
    'temperature': 'तापमान',
    'humidity': 'नमी',
    'rainfall': 'वर्षा',
    'soilHealth': 'मृदा स्वास्थ्य',
    'moisture': 'नमी',
    'waterStorage': 'जल भंडारण',
    'tankLevel': 'टैंक स्तर',
    'liters': 'लीटर',
    'cropRecommendation': 'फसल सिफारिश',
    'getRecommendation': 'सिफारिश प्राप्त करें',
    'season': 'मौसम',
    'soilType': 'मिट्टी का प्रकार',
    'altitude': 'ऊंचाई (मीटर)',
    'selectSeason': 'मौसम चुनें',
    'kharif': 'खरीफ',
    'rabi': 'रबी',
    'zaid': 'जायद',
    'selectSoil': 'मिट्टी का प्रकार चुनें',
    'alluvial': 'जलोढ़',
    'black': 'काली',
    'red': 'लाल',
    'laterite': 'लैटेराइट',
    'marketPrices': 'बाजार मूल्य',
    'crop': 'फसल',
    'price': 'मूल्य (प्रति क्विंटल)',
    'change': 'बदलाव',
    'iotData': 'IoT सेंसर डेटा',
    'communityForum': 'सामुदायिक मंच',
    'title': 'शीर्षक',
    'author': 'लेखक',
    'replies': 'उत्तर',
    'loadingRecommendations': 'हमारे विशेषज्ञों से सिफारिशें प्राप्त हो रही हैं...',
    'recommendationError': 'सिफारिशें प्राप्त नहीं हो सकीं। कृपया पुन: प्रयास करें।',
    'recommendationsForYou': 'आपके लिए सिफारिशें',
    'loadingWeather': 'मौसम लोड हो रहा है...',
    'weatherError': 'मौसम डेटा प्राप्त नहीं हो सका।',
    'lastUpdated': 'पिछला अपडेट',
    'mobilePlaceholder': '10 अंकों का मोबाइल नंबर दर्ज करें',
    'otpPlaceholder': '4 अंकों का ओटीपी दर्ज करें',
    'otpSent': 'ओटीपी आपके मोबाइल पर सफलतापूर्वक भेज दिया गया है!',
    'invalidOtp': 'अमान्य ओटीपी। कृपया पुन: प्रयास करें।',
    'invalidMobile': 'कृपया एक वैध 10-अंकीय मोबाइल नंबर दर्ज करें।',
    'resendOtp': 'पुनः ओटीपी भेजें',
    'advertisements': 'विशेष रुप से प्रदर्शित उत्पाद',
    'loadAds': 'उत्पाद दिखाएँ',
    'loadingAds': 'विज्ञापन लोड हो रहे हैं...',
    'adsError': 'विज्ञापन लोड नहीं हो सके।',
    'learnMore': 'और जानें',
    'governmentSchemes': 'सरकारी योजनाएं',
    'loadingSchemes': 'योजनाएं लोड हो रही हैं...',
    'schemesError': 'योजनाएं लोड नहीं हो सकीं।',
    'issuingBody': 'जारी करने वाला निकाय',
    'benefits': 'मुख्य लाभ',
    'eligibility': 'पात्रता',
    'officialLink': 'आधिकारिक लिंक',
    'chat': 'चैट',
    'searchUsers': 'उपयोगकर्ताओं को खोजें...',
    'newGroup': 'नया समूह',
    'createGroup': 'समूह बनाएं',
    'groupName': 'समूह का नाम',
    'selectMembers': 'सदस्य चुनें',
    'create': 'बनाएं',
    'cancel': 'रद्द करें',
    'typeMessage': 'एक संदेश लिखें...',
    'noConversation': 'चैटिंग शुरू करने के लिए एक वार्तालाप चुनें',
    'yearlyRainfallPrediction': 'वार्षिक वर्षा का पूर्वानुमान',
    'locationJorethang': 'जोरथांग, सिक्किम',
    'rainfall_mm': 'वर्षा (मिमी)',
    'aiAssistant': 'एग्रो असिस्टेंट',
    'aiWelcomeMessage': 'नमस्ते! मैं आपका एग्रो असिस्टेंट हूं। आज मैं आपकी खेती में कैसे मदद कर सकता हूं?',
    'aiError': 'क्षमा करें, मुझे कनेक्ट करने में समस्या आ रही है। कृपया बाद में पुन: प्रयास करें।',
  },
  [Language.NE]: {
    'appTitle': 'एग्रोस्मार्ट',
    'loginTitle': 'फेरि स्वागत छ',
    'loginSubtitle': 'OTP मार्फत आफ्नो ड्यासबोर्डमा लगइन गर्नुहोस्',
    'mobileLabel': 'मोबाइल नम्बर',
    'otpLabel': 'ओटीपी',
    'sendOtpButton': 'ओटीपी पठाउनुहोस्',
    'verifyButton': 'प्रमाणित गर्नुहोस् र लगइन गर्नुहोस्',
    'logout': 'लगआउट',
    'welcome': 'स्वागत छ',
    'dashboardTitle': 'किसान ड्यासबोर्ड',
    'weather': 'मौसम',
    'temperature': 'तापमान',
    'humidity': 'आर्द्रता',
    'rainfall': 'वर्षा',
    'soilHealth': 'माटोको स्वास्थ्य',
    'moisture': 'नमी',
    'waterStorage': 'पानी भण्डारण',
    'tankLevel': 'ट्याङ्की स्तर',
    'liters': 'लिटर',
    'cropRecommendation': 'बाली सिफारिस',
    'getRecommendation': 'सिफारिस प्राप्त गर्नुहोस्',
    'season': 'मौसम',
    'soilType': 'माटोको प्रकार',
    'altitude': 'उचाइ (मिटर)',
    'selectSeason': 'मौसम छान्नुहोस्',
    'kharif': 'खरीफ',
    'rabi': 'रबी',
    'zaid': 'जायद',
    'selectSoil': 'माटोको प्रकार छान्नुहोस्',
    'alluvial': 'पाँगो',
    'black': 'कालो',
    'red': 'रातो',
    'laterite': 'लेटेराइट',
    'marketPrices': 'बजार मूल्य',
    'crop': 'बाली',
    'price': 'मूल्य (प्रति क्विन्टल)',
    'change': 'परिवर्तन',
    'iotData': 'IoT सेन्सर डाटा',
    'communityForum': 'सामुदायिक फोरम',
    'title': 'शीर्षक',
    'author': 'लेखक',
    'replies': 'प्रतिक्रियाहरू',
    'loadingRecommendations': 'हाम्रा विज्ञहरूबाट सिफारिसहरू प्राप्त गर्दै...',
    'recommendationError': 'सिफारिसहरू प्राप्त गर्न सकिएन। कृपया फेरि प्रयास गर्नुहोस्।',
    'recommendationsForYou': 'तपाईंको लागि सिफारिसहरू',
    'loadingWeather': 'मौसम लोड हुँदैछ...',
    'weatherError': 'मौसम डाटा प्राप्त गर्न सकिएन।',
    'lastUpdated': 'पछिल्लो पटक अद्यावधिक',
    'mobilePlaceholder': '१०-अंकको मोबाइल नम्बर प्रविष्ट गर्नुहोस्',
    'otpPlaceholder': '४-अंकको OTP प्रविष्ट गर्नुहोस्',
    'otpSent': 'OTP तपाईंको मोबाइलमा सफलतापूर्वक पठाइयो!',
    'invalidOtp': 'अमान्य OTP। कृपया फेरि प्रयास गर्नुहोस्।',
    'invalidMobile': 'कृपया एक मान्य १०-अंकको मोबाइल नम्बर प्रविष्ट गर्नुहोस्।',
    'resendOtp': 'OTP फेरि पठाउनुहोस्',
    'advertisements': 'विशेष उत्पादनहरू',
    'loadAds': 'उत्पादनहरू देखाउनुहोस्',
    'loadingAds': 'विज्ञापनहरू लोड हुँदैछ...',
    'adsError': 'विज्ञापनहरू लोड गर्न सकिएन।',
    'learnMore': 'थप जान्नुहोस्',
    'governmentSchemes': 'सरकारी योजनाहरू',
    'loadingSchemes': 'योजनाहरू लोड हुँदैछ...',
    'schemesError': 'योजनाहरू लोड गर्न सकिएन।',
    'issuingBody': 'जारी गर्ने निकाय',
    'benefits': 'मुख्य लाभहरू',
    'eligibility': 'योग्यता',
    'officialLink': 'आधिकारिक लिङ्क',
    'chat': 'च्याट',
    'searchUsers': 'प्रयोगकर्ताहरू खोज्नुहोस्...',
    'newGroup': 'नयाँ समूह',
    'createGroup': 'समूह बनाउनुहोस्',
    'groupName': 'समूहको नाम',
    'selectMembers': 'सदस्यहरू छान्नुहोस्',
    'create': 'बनाउनुहोस्',
    'cancel': 'रद्द गर्नुहोस्',
    'typeMessage': 'सन्देश लेख्नुहोस्...',
    'noConversation': 'च्याट गर्नका लागि एक कुराकानी छान्नुहोस्',
    'yearlyRainfallPrediction': 'वार्षिक वर्षा पूर्वानुमान',
    'locationJorethang': 'जोरेथाङ, सिक्किम',
    'rainfall_mm': 'वर्षा (मिमी)',
    'aiAssistant': 'एग्रो असिस्टेन्ट',
    'aiWelcomeMessage': 'नमस्ते! म तपाईंको एग्रो असिस्टेन्ट हुँ। आज म तपाईंको खेतीमा कसरी मद्दत गर्न सक्छु?',
    'aiError': 'माफ गर्नुहोस्, मलाई जडान गर्न समस्या भइरहेको छ। कृपया पछि फेरि प्रयास गर्नुहोस्।',
  }
};